version: '3'
name: rmi
services:
    server:
        build:
            context: ./
            dockerfile: server/Dockerfile
        image: ziinahzoor/rmi-server-sd2023
        container_name: rmi-server-container
        hostname: rmi-server
        ports: [506:506]
        networks: [rminetwork]
    client:
        build:
            context: ./
            dockerfile: client/Dockerfile
        image: ziinahzoor/rmi-client-sd2023
        container_name: rmi-client-container
        stdin_open: true
        networks:
            - rminetwork
networks:
    rminetwork:
        driver: bridge
